version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: attendance-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: attendance-backend
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/attendance_system
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    container_name: attendance-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  mongo_data:
